### ISSUE TITLE
Plan not being executed, no error msg.

### ISSUE THREAD

**Issue by jarkomes** [Yelp/kafka-utils#119]
Dear,

When using the kafka-cluster-manager tool, I get the follow error:

> kafka-cluster-manager --cluster-type prod --cluster-name cluster-1 set_replication_factor --topic GPS_00 2
> INFO:kazoo.client:Connecting to SNIP:2181
> INFO:kazoo.client:Zookeeper connection established, state: CONNECTED
> INFO:kafka-zookeeper-manager:Fetching current cluster-topology from Zookeeper...
> INFO:SetReplicationFactorCmd:Decreasing topic GPS_00 replication factor from 4 to 2.
> INFO:SetReplicationFactorCmd:Total number of actions before reduction: 16.
> INFO:SetReplicationFactorCmd:Number of partition changes: 16. Number of leader-only changes: 0
> INFO:SetReplicationFactorCmd:Proposed plan assignment {'version': 1, 'partitions': [{'topic': u'GPS_00', 'partition': 9, 'replicas': [2, 6]}, {'topic': u'GPS_00', 'partition': 4, 'replicas': [4, 6]}, {'topic': u'GPS_00', 'partition': 10, 'replicas': [0, 5]}, {'topic': u'GPS_00', 'partition': 5, 'replicas': [0, 5]}, {'topic': u'GPS_00', 'partition': 11, 'replicas': [4, 0]}, {'topic': u'GPS_00', 'partition': 6, 'replicas': [2, 6]}, {'topic': u'GPS_00', 'partition': 12, 'replicas': [0, 5]}, {'topic': u'GPS_00', 'partition': 7, 'replicas': [3, 2]}, {'topic': u'GPS_00', 'partition': 13, 'replicas': [1, 2]}, {'topic': u'GPS_00', 'partition': 14, 'replicas': [3, 5]}, {'topic': u'GPS_00', 'partition': 15, 'replicas': [1, 5]}, {'topic': u'GPS_00', 'partition': 0, 'replicas': [1, 2]}, {'topic': u'GPS_00', 'partition': 1, 'replicas': [3, 4]}, {'topic': u'GPS_00', 'partition': 2, 'replicas': [3, 4]}, {'topic': u'GPS_00', 'partition': 8, 'replicas': [3, 1]}, {'topic': u'GPS_00', 'partition': 3, 'replicas': [4, 6]}]}
> INFO:SetReplicationFactorCmd:Proposed-plan actions count: 16
> **INFO:SetReplicationFactorCmd:Proposed plan won't be executed.**
> INFO:kazoo.client:Closing connection to SNIP:2181
> INFO:kazoo.client:Zookeeper session lost, state: CLOSED

What could be the reason? Am I missing a flag which is not documented maybe?

Thanks!
Jarko

**Comment by jarkomes** [comment]
seems I needed the --apply flag. Closing the issue.

**Comment by fede1024** [comment]
The info message could be improved (see #120).
