### ISSUE TITLE
Support other commands to start and stop kafka

### ISSUE THREAD

**Issue by simplesteph** [Yelp/kafka-utils#135]
For my setup, I have kafka running within Docker, so stopping and starting kafka isn't as straightforward as `sudo service kafka stop`. 

I'm going to submit a PR to support other options to start and stop kafka. This is not dangerous in my opinion, because it the power user already has ssh access to the Kafka Host.

**Comment by ecanzonieri** [comment]
I think this is a valid use case. Feel free to post a pr.

**Comment by simplesteph** [comment]
@ecanzonieri PR submitted
