### ISSUE TITLE
Guidance on how to use task?

### ISSUE THREAD

**Issue by simplesteph** [Yelp/kafka-utils#139]
There's a concept of prestart task and prestop task for the rolling restart.
Can we see an example of how to use those? I couldn't see it being documented anywhere. 

Thanks!

**Comment by neoeahit** [comment]
Hi @simplesteph,

Thanks for pointing it out. I am adding it in the documentation as part of https://github.com/Yelp/kafka-utils/pull/140

Hope it helps!

**Comment by yzernik** [comment]
Fixed in #140 .
