### ISSUE TITLE
kafka-consumer-manager doesn't work with kafka 2.1

### ISSUE THREAD

**Issue by boniek83** [Yelp/kafka-utils#214]
Probably due to group metadata changes in new kafka. Similar problem in burrow: https://github.com/linkedin/Burrow/issues/505

**Comment by klass-ivan** [comment]
Any updates on this? I'm trying to use kafka-consumer-manager on 2.1 which result in ``` line 892, in check_version
    raise Errors.NoBrokersAvailable()```  but I'm not 100% sure if it's because of this issue or configuration problem
