### ISSUE TITLE
Unable to use SSH Keys to log into servers

### ISSUE THREAD

**Issue by Asara** [Yelp/kafka-utils#46]
I have my ssh key distributed to all my kafka servers, but kafka-utils asks for a password regardless.

**Comment by ecanzonieri** [comment]
It's happened to me a couple of times, but then if I type in a random password it connects properly using the ssh key.  Did you enable ssh agent forwarding? Or you are running this from where you have access to the private key?

**Comment by Asara** [comment]
I am trying to script around Kafka Utils.  Running from where I have access to the private key.

**Comment by Asara** [comment]
Alright I've tried typing random stuff into the prompt but it doesn't seem to work.

**Comment by Asara** [comment]
Also doesn't work with an ssh agent.

**Comment by Asara** [comment]
Ignore.  It works when setting ssh-agent.  

Thanks!
